services:
  elite-fitness-next: 
    container_name: elite-fitness-next
    restart: always
    image: node:20.10.0
    environment:
      - PORT=3000

    ports:
      - "0.0.0.0:4000:3000"

    env_file:
      - .env.local

    volumes:
      - ./:/usr/src/elite-fitness-next
      
    working_dir: /usr/src/elite-fitness-next

    networks:
      - client-network
     
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge


#elite-fitness-next: localhost:4000 <==> container:3001
#elite-fitness-api: localhost:4001 <==> container:3002
#elite-fitness-batch: localhost:4002 <==> container:3003
