export enum CommentStatus {
	ACTIVE = 'ACTIVE',
	DELETE = 'DELETE',
}

export enum CommentGroup {
	MEMBER = 'MEMBER',
	ARTICLE = 'ARTICLE',
	PROPERTY = 'PROPERTY',
	PRODUCT = 'PRODUCT',
	CLOTHES = 'CLOTHES',
	EQUIPMENT = 'EQUIPMENT',
	COMMENT = 'COMMENT',
}
