export enum NoticeCategory {
	FAQ = 'FAQ',
	TERMS = 'TERMS',
	ANNOUNCEMENT = 'ANNOUNCEMENT',
	UPDATE = 'UPDATE',
	MAINTENANCE = 'MAINTENANCE',
	PROMOTION = 'PROMOTION',
	POLICY = 'POLICY',
	EVENT = 'EVENT',
	ALERT = 'ALERT',
}

export enum NoticeStatus {
	HOLD = 'HOLD',
	ACTIVE = 'ACTIVE',
	DELETE = 'DELETE',
}
