export enum PropertyType {
	FITNESS_GYM = 'FITNESS_GYM',
	BOXING_GYM = 'BOXING_GYM',
	YOGA_STUDIO = 'YOGA_STUDIO',
	SWIMMING_POOL = 'SWIMMING_POOL',
}

export enum PropertyStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum PropertyLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
}
